---
# Default variables for CNI plugin role

calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"
calico_manifest_path: /tmp/calico.yaml