---
# Ansible inventory for QEMU-based Kubernetes cluster on Apple Silicon
# VMs are accessed via localhost with unique SSH ports

all:
  children:
    control_plane:
      hosts:
        control-plane-1:
          ansible_host: 127.0.0.1
          ansible_port: 50022
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/control-plane-1/qemu/private_key

    workers:
      hosts:
        worker-1:
          ansible_host: 127.0.0.1
          ansible_port: 50023
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/worker-1/qemu/private_key
        worker-2:
          ansible_host: 127.0.0.1
          ansible_port: 50024
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/worker-2/qemu/private_key

    k8s_cluster:
      children:
        control_plane:
        workers:
