---
all:
  children:
    control_plane:
      hosts:
        control-plane-1:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/control-plane-1/virtualbox/private_key

    workers:
      hosts:
        worker-1:
          ansible_host: 192.168.56.20
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/worker-1/virtualbox/private_key
        worker-2:
          ansible_host: 192.168.56.21
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/worker-2/virtualbox/private_key

    k8s_cluster:
      children:
        control_plane:
        workers:
